#!/bin/zsh

# This script formats sources generated by STM32CubeMX

CLANG_FORMAT_FILE=../libraries/klangstrom-stm32/.clang-format
KLST_STM32_LIB_PATH=../libraries/klangstrom-stm32
DIRECTORIES_FILE=$(dirname "$(realpath "$0")")/KLST_PANDA-directories.txt

# Check if the directories file exists
if [ ! -f "$DIRECTORIES_FILE" ]; then
    echo "Error: Directories file $DIRECTORIES_FILE does not exist."
    exit 1
fi

# Read directories from the file and call clang-format-folder.sh for each
while IFS= read -r REL_DIR; do
    if [ -n "$REL_DIR" ]; then
        ./clang-format-folder.sh "$KLST_STM32_LIB_PATH/$REL_DIR" "$CLANG_FORMAT_FILE"
    fi
done < "$DIRECTORIES_FILE"
